version: "3.8"

services:
  db:
    image: postgres:14
    container_name: envyous_postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: envyous2025_AMB
      POSTGRES_DB: enyous_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
